favicon: null
name: SNØLYKKAN
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
purpose: []
color:
  saturation: 0.7506588224787265
  brandStrength: 0
  rhythmicContrast: 0.8631205831188709
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#7f7f7f'
    - '#4f4f4f'
    - '#afafaf'
  lightness: 0.443637173390016
typography_spectrum: 0.48614
cta:
  bucket: null
  version: null
  domain: null
layout_spectrum: 0.9574468
analytics:
  twitter: null
  google: null
  facebook: null
