name: SNØLYKKAN
favicon: null
layout_spectrum: 0.9574468
typography_spectrum: 0.48614
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: Renegades of Snowequality
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-75901857-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#7f7f7f'
    - '#4f4f4f'
    - '#afafaf'
  brandStrength: 0
  lightness: 0.443637173390016
  saturation: 0.7506588224787265
  rhythmicContrast: 0.8631205831188709
purpose: []
