name: SNØLYKKAN
favicon: null
layout_spectrum: 1
typography_spectrum: 0.48614
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#7f7f7f'
    - '#4f4f4f'
    - '#afafaf'
  brandStrength: 0
  lightness: 0.44363717339001596
  saturation: 0.7506588224787265
  rhythmicContrast: 0.8631205831188709
purpose: []
